THEME=JRC
COLORTHEME=dolphin

all:
	pandoc 03_Functions_Programming.md -t beamer -V theme:${THEME} -V colortheme:${COLORTHEME} -o 03_Functions_Programming.pdf

clean:
	rm 03_Functions_Programming.pdf
